grafana:
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
    datasources:
      enabled: true
      defaultDatasourceEnabled: true

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 2d
    scrapeInterval: 15s
    evaluationInterval: 15s
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: {}
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        memory: 1Gi

alertmanager:
  alertmanagerSpec:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 25m
      memory: 32Mi