grafana:
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
    datasources:
      enabled: true
      defaultDatasourceEnabled: true

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 2d
    sruleSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: { }
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: { }
    evaluationInterval: 5s
    scrapeInterval: 5s
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        memory: 1Gi

alertmanager:
  alertmanagerSpec:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 25m
      memory: 32Mi