apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop.fullname" . }}-api
  labels:
    app: shop-api
    {{- toYaml .Values.commonLabels | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: shop-api
