apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shop.fullname" . }}-postgres-auth
  labels:
    app: shop-postgres
    {{- toYaml .Values.commonLabels | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.auth.user | quote }}
  password: {{ .Values.postgres.auth.password | quote }}