apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop.fullname" . }}-postgres
  labels:
    app: shop-postgres
    {{- toYaml .Values.commonLabels | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    app: shop-postgres
