{{- if .Values.api.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "shop.fullname" . }}-api
  labels:
    release: monitoring
    app: shop-api
    owner: {{ .Values.commonLabels.owner | quote }}
    env: {{ .Values.commonLabels.env | quote }}
spec:
  jobLabel: app
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: shop-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}