apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shop.fullname" . }}-worker
  labels:
    app: shop-worker
    {{- toYaml .Values.commonLabels | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: shop-worker
  template:
    metadata:
      labels:
        app: shop-worker
        {{- toYaml .Values.commonLabels | nindent 8 }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          env:
            - name: POSTGRES_HOST
              value: {{ include "shop.fullname" . }}-postgres
            - name: POSTGRES_PORT
              value: {{ .Values.postgres.service.port | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.auth.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.auth.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.db | quote }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
