apiVersion: v1
kind: Pod
metadata:
  name: bad-registry
  labels:
    app: bad-test
    owner: me
    env: dev
spec:
  containers:
    - name: c
      image: evil.example.com/malware:1.0
      command: ["sleep", "3600"]
      resources:
        limits:
          cpu: "100m"
          memory: "64Mi"
        requests:
          cpu: "100m"
          memory: "64Mi"