apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-service
  namespace: default
  labels:
    release: kube-prom
spec:
  selector:
    matchLabels:
      app: api-service-api-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s